
volumes:
    neo4j-data:
    neo4j-backups:

services:
    sggcityneo4j:
        container_name: sgg-city-neo4j
        image: neo4j:2025.06.0-community-bullseye
        ports:
            - "7474:7474"
            - "7687:7687"
        env_file:
            - ./env_files/.neo4j_env
        environment:
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_filep_use__neo4j__config=true
            - NEO4J_PLUGINS=\[\"apoc\"\]
        volumes:
            - neo4j-data:/data
            - neo4j-backups:/backups
